### ISSUE TITLE
Bold Number

### ISSUE THREAD

**Issue by Balaarizalu** [Janworks/AoETechTree#3]
https://s3.postimg.org/nvd336ifn/Screenshot_18.png
Could you fix this bug, please?

**Comment by JanWichelmann** [comment]
Sorry for the late response, I am very busy currently :-(

Unfortunately I cannot really reproduce this behaviour, or find a reason for it. As all the formatting is done by some game functions, I doubt there is an easy fix for that. Could you upload your DAT and DLL files here?

**Comment by Balaarizalu** [comment]
I'll send the file via email.

**Comment by Balaarizalu** [comment]
ou wow Thanks Jan
